# Stage 1 - the build-deps
FROM node:14 as build-deps
WORKDIR /app
COPY  ["package.json", "package-lock.json", "node_modules", "."]
COPY ./public .
COPY . .
RUN npm run build

# Stage 2 - the production environment
FROM nginx
COPY --from=build-deps /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]