# Stage 1 - the build-deps
FROM node:14.16.0-alpine3.10 as build-deps
WORKDIR /app
COPY  ["package.json", "package-lock.json", "node_modules", "."]
COPY ./public .
COPY . .
# Get build argument and set environment variable
ARG API_ENDPOINT
ENV REACT_APP_API_ENDPOINT=$API_ENDPOINT
# Build react-app
RUN npm run build

# Stage 2 - the production environment
FROM nginx
COPY --from=build-deps /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]