version: "3.9"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "ead8686ba57479778a76e"
      MYSQL_USER: "btcn_03"
      MYSQL_PASSWORD: "19e5a718a54a9fe0559dfbce6908"
      MYSQL_DATABASE: "btcn_03"
    container_name: golang_db
    volumes:
      - mysql_data:/var/lib/mysql
  api:
    image: nhlong/backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: golang_app
    environment:
      DB_CONN_STR: "btcn_03:19e5a718a54a9fe0559dfbce6908@tcp(golang_db:3306)/btcn_03?charset=utf8mb4&parseTime=True&loc=Local"
    build:
      context: ./backend
  fe: 
    image: nhlong/frontend
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      API_ENDPOINT: golang_db/v1/
    container_name: react_app
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.prod

volumes:
  mysql_data: