version: "3.9"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "ead8686ba57479778a76e"
      MYSQL_USER: "btcn_03"
      MYSQL_PASSWORD: "19e5a718a54a9fe0559dfbce6908"
      MYSQL_DATABASE: "btcn_03"
    container_name: golang_db
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    image: nhlong/backend
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      DB_CONN_STR: "btcn_03:19e5a718a54a9fe0559dfbce6908@tcp(golang_db:3306)/btcn_03?charset=utf8mb4&parseTime=True&loc=Local"
    build:
      context: ./backend

  balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api   
    ports:
      - "4000:4000"

  fe: 
    image: nhlong/frontend
    ports:
      - "80:80"
    depends_on:
      - api
    container_name: react_app
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.prod
      args:
        API_ENDPOINT: http://localhost:4000/v1/

volumes:
  mysql_data: